### PR TITLE
update readme style

### PR DESCRIPTION
**Pull request by ungoldman**
Updates README.md to match webtorrent & webtorrent-app readme style.

See https://github.com/ungoldman/webtorrent-cli/tree/readme#readme for a preview.

### CODE REVIEW

**Comment by rom1504** [comment]
I guess webtorrent readme look a little bit better with that html, but is that really worth breaking the point of a .md file ? (i.e. being readable without a render engine (unlike html))

**Comment by ungoldman** [comment]
Just making the style consistent with the other two webtorrent repos @rom1504. If text editor readability is more important then we should revert the other two to their former styles, but that's up to @feross

**Comment by feross** [comment]
I agree with @rom1504 that the README should be readable, but I think it's fine to do this just for the header. The rest of the README is still plain markdown.

**Comment by feross** [comment]
Thanks @ungoldman! Eventually, would be cool to make custom icons for each app type.

**Pull request merged**
