### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by pataquets**
Add Dockerfile to enable image building.
By now, I use the official Node image, 'onbuild' tag. More info at https://hub.docker.com/_/node/ . Should the build be pinned to any specific version, let me know.

Build:

```
$ docker build -t webtorrent-cli .
```

Run:

```
$ docker run -rm -it --name webtorrent -p 8000:8000 webtorrent-cli <magnet-link>
```

FYI, there's a still quicker to test, already built image on my Docker Hub. Test it by running:

```
$ docker run -rm -it --name webtorrent -p 8000:8000 pataquets/webtorrent-cli <magnet-link>
```

Using `--rm` instead of `-d` makes the container not go background and it to be deleted after stop. Stop it by `CTRL+C`'ing it. Also, you might want to add one (or more) `-v /host/dir/path:/container/path/` options in order to mount host's directories into the container to use `.torrent` files.

More optional improvements to come:
- Create an 'official' automated build at Docker Hub for the image: https://docs.docker.com/docker-hub/builds/

### CODE REVIEW

**Comment by pataquets** [comment]
@feross: Bump

**Comment by feross** [comment]
Thanks for the PR, but I don't use Docker and I don't understand why this can't be done in your own repo.

**Comment by pataquets** [comment]
Thanks for the review @feross .
Aside from easing non-devel people using and supporting the tool, more and more devs are using Docker as a repeatable local dev/test environment in their workflows. For newly entering contributors, the ```docker build```/```docker run``` dev/test setup lowers the entry barrier a lot.
It also keeps the Docker recipe a canonical place where it is maintained and discussed and where ppl can contribute improvements to, or at least have a minimal base to start from. For people using Docker (like myself) in absence of an official one, just pulling upstream changes it's all what's needed to build one. In addition, Docker-friendliness gives confidence to anyone thinking to step up as Docker official image maintainer. It also might help yourself to adopt Docker as just another way of packaging and distributing the software by just creating an official Automated Build in Docker Hub (has even a image pulls counter). I think that with time, more people will ask for an 'official' (automatically built from source, that is trustable) Docker Hub image.
Overall, makes people aware of Docker as another runtime environment and can attract other useful contributions in the long run, IMHO, even if you are not using it (by now :wink:). If you have problems or other requirements with using Docker, I can help you, also.
It can't hurt having just another tool at everyone's disposal, even if you warn clearly in the readme that it is not officially supported. Said warning might even attract more hands eager to help.

**Comment by iovis9** [comment]
> Aside from easing non-devel people using and supporting the tool

I think people that knows how to use Docker are proficient enough to know how to use or install this package.

**Comment by feross** [comment]
> For newly entering contributors, the docker build/docker run dev/test setup lowers the entry barrier a lot.

For Node.js users, it's already really easy to get started:

```
npm install
npm test
```

I appreciate where you're coming from, but I respectfully disagree. Docker doesn't solve any problems that I have.

**Pull request closed without merging**
